#!/home/fran/anaconda2/envs/amuse/bin/python
import sys
import os



if __name__ == '__main__':
    use_sockets = len(sys.argv) > 1
    if use_sockets:
        portnumber = int(sys.argv[1])
        host = sys.argv[2]
        usempi= sys.argv[3] == "true" or sys.argv[3] == "1"
    else:
        usempi = True
        host = None
        portnumber = -1
        
    syspath = ('/media/fran/data1/amuse/src','/media/fran/data1/amuse','/media/fran/data1/amuse/support','/media/fran/data1/amuse/src/amuse/community/mosse','/media/fran/data1/amuse/src','/media/fran/data1/amuse/test','/home/fran/anaconda2/envs/amuse/lib/python27.zip','/home/fran/anaconda2/envs/amuse/lib/python2.7','/home/fran/anaconda2/envs/amuse/lib/python2.7/plat-linux2','/home/fran/anaconda2/envs/amuse/lib/python2.7/lib-tk','/home/fran/anaconda2/envs/amuse/lib/python2.7/lib-old','/home/fran/anaconda2/envs/amuse/lib/python2.7/lib-dynload','/home/fran/.local/lib/python2.7/site-packages','/home/fran/anaconda2/envs/amuse/lib/python2.7/site-packages','/media/fran/data1/amuse/src/amuse/community/mosse')
    existing_syspath = set(sys.path)
    for x in syspath:
        if not x in existing_syspath:
            sys.path.insert(0,x)

    
    if usempi:
        from mpi4py import MPI
        from amuse.rfi.channel import MpiChannel
        MpiChannel.ensure_mpi_initialized()
        
    from amuse.rfi import core

    import mosse_cython
    from amuse.community.mosse.interface import MOSSEInterface

    instance = mosse_cython

    from amuse.rfi.python_code import CythonImplementation
    
    x = CythonImplementation(instance, MOSSEInterface)
    
    if use_sockets:
        x.start_socket(portnumber, host)
    else:
        x.start()
